"use strict";

const MAIN_BUNDLE_PATTERN = /^main-[^.]+\.js$/;
const WEBVIEW_ASSET_PATTERN = /^app-initial-[^.]+\.js$/;
const CONSOLE_IPC_MARKER = "codex-linux-interactive-console-ipc";
const CONSOLE_RUNTIME_MARKER = "codex-linux-interactive-console-runtime";

function warn(message) {
  console.warn(`WARN: ${message} - skipping interactive-console patch`);
}

function consoleIpcRuntimeSource() {
  return [
    `/*${CONSOLE_IPC_MARKER}*/`,
    `;(()=>{`,
    `if(typeof require!=="undefined"&&typeof electron!=="undefined"||typeof require!=="undefined"){`,
    `try{`,
    `const {ipcMain}=require("electron");`,
    `const {PtyManager}=require("./features/interactive-console/pty-manager.js");`,
    `const manager=new PtyManager();`,
    `ipcMain.handle("zodex-console-sessions",()=>manager.listSessions());`,
    `ipcMain.handle("zodex-console-spawn",(e,opts)=>{`,
    `let s=manager.createSession(opts);`,
    `s.on("data",(chunk)=>{e.sender.send("zodex-console-data",{id:s.id,chunk});});`,
    `s.on("status",(st)=>{e.sender.send("zodex-console-status",{id:s.id,...st});});`,
    `s.on("waiting_for_input",(p)=>{e.sender.send("zodex-console-input-needed",{id:s.id,...p});});`,
    `return{id:s.id,status:s.status,command:s.command};`,
    `});`,
    `ipcMain.handle("zodex-console-input",(e,id,input,opts)=>manager.writeInput(id,input,opts));`,
    `ipcMain.handle("zodex-console-kill",(e,id,signal)=>manager.killSession(id,signal));`,
    `}catch(err){console.warn("WARN: zodex console ipc init failed",err);}`,
    `}`,
    `})();`,
  ].join("");
}

function consoleWebviewRuntimeSource() {
  return [
    `/*${CONSOLE_RUNTIME_MARKER}*/`,
    `;(()=>{`,
    `if(typeof window==="undefined")return;`,
    `let state={sessions:new Map,activeSessionId:null,isOpen:false,isMaximized:false};`,
    `function ansiToHtml(str){`,
    `if(!str)return"";`,
    `let s=String(str).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");`,
    `s=s.replace(/\\x1b\\[0?m/g,"</span>");`,
    `s=s.replace(/\\x1b\\[1m/g,"<span style='font-weight:bold;'>");`,
    `s=s.replace(/\\x1b\\[31m/g,"<span style='color:#f87171;'>");`,
    `s=s.replace(/\\x1b\\[32m/g,"<span style='color:#4ade80;'>");`,
    `s=s.replace(/\\x1b\\[33m/g,"<span style='color:#facc15;'>");`,
    `s=s.replace(/\\x1b\\[34m/g,"<span style='color:#60a5fa;'>");`,
    `s=s.replace(/\\x1b\\[35m/g,"<span style='color:#c084fc;'>");`,
    `s=s.replace(/\\x1b\\[36m/g,"<span style='color:#2dd4bf;'>");`,
    `s=s.replace(/\\x1b\\[90m/g,"<span style='color:#9ca3af;'>");`,
    `s=s.replace(/\\x1b\\[[0-9;]*[a-zA-Z]/g,"");`,
    `return s;`,
    `}`,
    `function renderDock(){`,
    `let dock=document.getElementById("zodex-terminal-dock");`,
    `if(!dock){`,
    `dock=document.createElement("div");`,
    `dock.id="zodex-terminal-dock";`,
    `dock.style.cssText="position:fixed;bottom:0;left:0;right:0;height:280px;background:#131418;border-top:1px solid rgba(255,255,255,0.14);box-shadow:0 -8px 24px rgba(0,0,0,0.45);z-index:9990;display:flex;flex-direction:column;font-family:'JetBrains Mono','Fira Code','Cascadia Code',monospace;font-size:12.5px;color:#e2e8f0;transition:transform 0.2s ease,height 0.2s ease;transform:translateY(100%);";`,
    `dock.innerHTML=\``,
    `<div id="zodex-dock-header" style="display:flex;align-items:center;justify-content:space-between;padding:6px 12px;background:#1a1b22;border-bottom:1px solid rgba(255,255,255,0.08);user-select:none;">`,
    `  <div style="display:flex;align-items:center;gap:10px;">`,
    `    <span style="font-weight:700;color:#38bdf8;display:flex;align-items:center;gap:6px;"><span style="font-size:14px;">&gt;_</span> Terminal</span>`,
    `    <div id="zodex-dock-tabs" style="display:flex;gap:4px;"></div>`,
    `  </div>`,
    `  <div style="display:flex;align-items:center;gap:8px;">`,
    `    <button id="zodex-dock-new" title="New Session" style="background:rgba(255,255,255,0.08);border:none;color:#94a3b8;padding:2px 8px;border-radius:4px;cursor:pointer;font-size:11px;">+ New</button>`,
    `    <button id="zodex-dock-clear" title="Clear Output" style="background:none;border:none;color:#94a3b8;cursor:pointer;font-size:12px;">Clear</button>`,
    `    <button id="zodex-dock-maximize" title="Maximize" style="background:none;border:none;color:#94a3b8;cursor:pointer;font-size:13px;">⤢</button>`,
    `    <button id="zodex-dock-close" title="Close" style="background:none;border:none;color:#94a3b8;cursor:pointer;font-size:14px;">✕</button>`,
    `  </div>`,
    `</div>`,
    `<div id="zodex-dock-output" style="flex:1;overflow-y:auto;padding:10px 14px;white-space:pre-wrap;word-break:break-all;line-height:1.45;background:#0d0e11;"></div>`,
    `<div id="zodex-dock-prompt" style="display:none;align-items:center;gap:8px;padding:8px 12px;background:#1e1f29;border-top:1px solid #38bdf8;box-shadow:0 -4px 12px rgba(56,189,248,0.15);">`,
    `  <span id="zodex-prompt-msg" style="color:#facc15;font-weight:600;font-size:12px;">🔒 Sudo Password:</span>`,
    `  <input id="zodex-prompt-input" type="password" style="flex:1;background:#0f1015;border:1px solid rgba(255,255,255,0.2);color:#fff;padding:4px 8px;border-radius:4px;outline:none;font-family:inherit;font-size:12px;" />`,
    `  <button id="zodex-prompt-submit" style="background:#0284c7;color:#fff;border:none;padding:4px 12px;border-radius:4px;cursor:pointer;font-size:11px;font-weight:600;">Submit ↵</button>`,
    `  <button id="zodex-prompt-cancel" style="background:rgba(255,255,255,0.1);color:#cbd5e1;border:none;padding:4px 8px;border-radius:4px;cursor:pointer;font-size:11px;">Cancel (Ctrl+C)</button>`,
    `</div>`,
    `<div id="zodex-dock-cli" style="display:flex;align-items:center;gap:6px;padding:6px 12px;background:#15161c;border-top:1px solid rgba(255,255,255,0.06);">`,
    `  <span style="color:#38bdf8;font-weight:bold;">$</span>`,
    `  <input id="zodex-cli-input" placeholder="Type command or input..." style="flex:1;background:none;border:none;color:#f1f5f9;outline:none;font-family:inherit;font-size:12px;" />`,
    `</div>\`;`,
    `document.body.appendChild(dock);`,
    `document.getElementById("zodex-dock-close").onclick=()=>window.__ZODEX_CONSOLE__.closeDock();`,
    `document.getElementById("zodex-dock-maximize").onclick=()=>{`,
    `state.isMaximized=!state.isMaximized;`,
    `dock.style.height=state.isMaximized?"75vh":"280px";`,
    `document.getElementById("zodex-dock-maximize").textContent=state.isMaximized?"🗗":"⤢";`,
    `};`,
    `document.getElementById("zodex-dock-clear").onclick=()=>{`,
    `let out=document.getElementById("zodex-dock-output");if(out)out.innerHTML="";`,
    `if(state.activeSessionId&&state.sessions.has(state.activeSessionId))state.sessions.get(state.activeSessionId).output="";`,
    `};`,
    `document.getElementById("zodex-dock-new").onclick=async()=>{`,
    `await window.__ZODEX_CONSOLE__.spawn({command:"bash"});`,
    `};`,
    `let promptInput=document.getElementById("zodex-prompt-input");`,
    `let submitPrompt=async()=>{`,
    `if(!state.activeSessionId)return;`,
    `let val=promptInput.value;`,
    `let isPass=promptInput.type==="password";`,
    `promptInput.value="";`,
    `document.getElementById("zodex-dock-prompt").style.display="none";`,
    `await window.__ZODEX_CONSOLE__.sendInput(state.activeSessionId,val,isPass);`,
    `};`,
    `document.getElementById("zodex-prompt-submit").onclick=submitPrompt;`,
    `promptInput.onkeydown=(e)=>{if(e.key==="Enter")submitPrompt();};`,
    `document.getElementById("zodex-prompt-cancel").onclick=async()=>{`,
    `if(state.activeSessionId)await window.__ZODEX_CONSOLE__.kill(state.activeSessionId,"SIGINT");`,
    `document.getElementById("zodex-dock-prompt").style.display="none";`,
    `};`,
    `let cliInput=document.getElementById("zodex-cli-input");`,
    `cliInput.onkeydown=async(e)=>{`,
    `if(e.key==="Enter"){`,
    `let val=cliInput.value;cliInput.value="";`,
    `if(!state.activeSessionId){await window.__ZODEX_CONSOLE__.spawn({command:val||"bash"});}else{await window.__ZODEX_CONSOLE__.sendInput(state.activeSessionId,val,false);}`,
    `}`,
    `};`,
    `}`,
    `let toggleBtn=document.getElementById("zodex-terminal-toggle-btn");`,
    `if(!toggleBtn){`,
    `toggleBtn=document.createElement("button");`,
    `toggleBtn.id="zodex-terminal-toggle-btn";`,
    `toggleBtn.style.cssText="position:fixed;bottom:14px;right:20px;z-index:9980;background:#1e293b;border:1px solid rgba(255,255,255,0.15);color:#38bdf8;padding:6px 12px;border-radius:20px;cursor:pointer;font-family:monospace;font-size:12px;font-weight:600;display:flex;align-items:center;gap:6px;box-shadow:0 4px 12px rgba(0,0,0,0.3);transition:all 0.15s ease;";`,
    `toggleBtn.innerHTML="<span>&gt;_</span> Terminal";`,
    `toggleBtn.onmouseenter=()=>toggleBtn.style.background="#334155";`,
    `toggleBtn.onmouseleave=()=>toggleBtn.style.background="#1e293b";`,
    `toggleBtn.onclick=()=>window.__ZODEX_CONSOLE__.toggleDock();`,
    `document.body.appendChild(toggleBtn);`,
    `}`,
    `}`,
    `function updateSessionOutput(id,chunk){`,
    `if(!state.sessions.has(id))state.sessions.set(id,{id,output:"",status:"running"});`,
    `let s=state.sessions.get(id);`,
    `s.output=(s.output||"")+chunk;`,
    `if(state.activeSessionId===id){`,
    `let out=document.getElementById("zodex-dock-output");`,
    `if(out){out.innerHTML+=ansiToHtml(chunk);out.scrollTop=out.scrollHeight;}`,
    `}`,
    `}`,
    `function updateSessionTabs(){`,
    `let tabs=document.getElementById("zodex-dock-tabs");`,
    `if(!tabs)return;`,
    `tabs.innerHTML="";`,
    `for(let[id,s]of state.sessions.entries()){`,
    `let btn=document.createElement("button");`,
    `btn.style.cssText=\`background:\${id===state.activeSessionId?"#0284c7":"rgba(255,255,255,0.06)"};color:#fff;border:none;padding:2px 8px;border-radius:4px;cursor:pointer;font-size:11px;font-family:inherit;\`;`,
    `btn.textContent=(s.command||"bash")+" #"+id.slice(-4);`,
    `btn.onclick=()=>{`,
    `state.activeSessionId=id;`,
    `let out=document.getElementById("zodex-dock-output");`,
    `if(out){out.innerHTML=ansiToHtml(s.output);out.scrollTop=out.scrollHeight;}`,
    `updateSessionTabs();`,
    `};`,
    `tabs.appendChild(btn);`,
    `}`,
    `}`,
    `window.__ZODEX_CONSOLE__={`,
    `async listSessions(){return window.electron?.ipcRenderer?.invoke("zodex-console-sessions")||[];},`,
    `async spawn(opts){`,
    `let res=await window.electron?.ipcRenderer?.invoke("zodex-console-spawn",opts);`,
    `if(res&&res.id){`,
    `state.sessions.set(res.id,{id:res.id,command:opts?.command||"bash",output:"",status:res.status});`,
    `state.activeSessionId=res.id;`,
    `window.__ZODEX_CONSOLE__.openDock();`,
    `updateSessionTabs();`,
    `}`,
    `return res;`,
    `},`,
    `async sendInput(id,input,isPassword=false){return window.electron?.ipcRenderer?.invoke("zodex-console-input",id,input,{isPassword});},`,
    `async kill(id,signal){return window.electron?.ipcRenderer?.invoke("zodex-console-kill",id,signal);},`,
    `openDock(){`,
    `renderDock();`,
    `let dock=document.getElementById("zodex-terminal-dock");`,
    `if(dock){dock.style.transform="translateY(0)";state.isOpen=true;}`,
    `},`,
    `closeDock(){`,
    `let dock=document.getElementById("zodex-terminal-dock");`,
    `if(dock){dock.style.transform="translateY(100%)";state.isOpen=false;}`,
    `},`,
    `toggleDock(){if(state.isOpen){window.__ZODEX_CONSOLE__.closeDock();}else{window.__ZODEX_CONSOLE__.openDock();}},`,
    `};`,
    `if(typeof window.electron!=="undefined"&&window.electron?.ipcRenderer){`,
    `window.electron.ipcRenderer.on("zodex-console-data",(e,data)=>{`,
    `if(data?.id){updateSessionOutput(data.id,data.chunk);}`,
    `});`,
    `window.electron.ipcRenderer.on("zodex-console-input-needed",(e,data)=>{`,
    `if(data?.id){`,
    `window.__ZODEX_CONSOLE__.openDock();`,
    `let pBox=document.getElementById("zodex-dock-prompt");`,
    `let pMsg=document.getElementById("zodex-prompt-msg");`,
    `let pInput=document.getElementById("zodex-prompt-input");`,
    `if(pBox&&pMsg&&pInput){`,
    `pBox.style.display="flex";`,
    `pMsg.textContent=data.isPassword?"🔒 Sudo Password:":(data.prompt||"Input needed:");`,
    `pInput.type=data.isPassword?"password":"text";`,
    `pInput.focus();`,
    `}`,
    `}`,
    `});`,
    `window.electron.ipcRenderer.on("zodex-console-status",(e,st)=>{`,
    `if(st?.id&&state.sessions.has(st.id)){`,
    `let s=state.sessions.get(st.id);s.status=st.status;s.exitCode=st.exitCode;`,
    `updateSessionOutput(st.id,"\\n[Process "+st.status+(st.exitCode!=null?" ("+st.exitCode+")":"")+"]\\n");`,
    `}`,
    `});`,
    `}`,
    `document.addEventListener("keydown",(e)=>{if(e.ctrlKey&&e.key==="\`"){e.preventDefault();window.__ZODEX_CONSOLE__.toggleDock();}});`,
    `if(document.readyState==="loading"){document.addEventListener("DOMContentLoaded",renderDock,{once:true});}else{renderDock();}`,
    `})();`,
  ].join("");
}

function applyMainBundlePatch(source) {
  try {
    if (typeof source !== "string") return source;
    if (source.includes(CONSOLE_IPC_MARKER)) return source;
    return `${source}\n${consoleIpcRuntimeSource()}\n`;
  } catch (error) {
    warn(`Main bundle patch error: ${error.message}`);
    return source;
  }
}

function applyWebviewAssetPatch(source) {
  try {
    if (typeof source !== "string") return source;
    if (source.includes(CONSOLE_RUNTIME_MARKER)) return source;
    return `${source}\n${consoleWebviewRuntimeSource()}\n`;
  } catch (error) {
    warn(`Webview asset patch error: ${error.message}`);
    return source;
  }
}

const descriptors = [
  {
    id: "interactive-console-main",
    phase: "main-bundle",
    order: 20_820,
    ciPolicy: "optional",
    pattern: MAIN_BUNDLE_PATTERN,
    missingDescription: "main process bundle",
    skipDescription: "interactive console main ipc patch",
    apply: (source) => applyMainBundlePatch(source),
  },
  {
    id: "interactive-console-webview",
    phase: "webview-asset",
    order: 20_821,
    ciPolicy: "optional",
    pattern: WEBVIEW_ASSET_PATTERN,
    missingDescription: "webview initial bundle",
    skipDescription: "interactive console webview runtime patch",
    apply: (source) => applyWebviewAssetPatch(source),
  },
];

module.exports = {
  CONSOLE_IPC_MARKER,
  CONSOLE_RUNTIME_MARKER,
  MAIN_BUNDLE_PATTERN,
  WEBVIEW_ASSET_PATTERN,
  applyMainBundlePatch,
  applyWebviewAssetPatch,
  consoleIpcRuntimeSource,
  consoleWebviewRuntimeSource,
  descriptors,
};
